name: QA Check

on:
  push:
    branches: [ Quality Assurance ]
  pull_request: 
    branches: [ Quality Assurance ]
  workflow_dispatch:

jobs: 
    qa:
      runs-on: windows-latest
      steps:
       - name: Checkout repo
         uses: actions/setup-python@v3

       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.x"

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install nbformat nbconvert

       - name: Run QA script
         run: python QA/QA.py
